/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppClienteRouteImport } from './routes/app.cliente'
import { Route as AppClienteRecompensasRouteImport } from './routes/app.cliente.recompensas'
import { Route as AppClienteQrRouteImport } from './routes/app.cliente.qr'
import { Route as AppClientePerfilRouteImport } from './routes/app.cliente.perfil'
import { Route as AppClienteInicioRouteImport } from './routes/app.cliente.inicio'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClienteRoute = AppClienteRouteImport.update({
  id: '/app/cliente',
  path: '/app/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClienteRecompensasRoute = AppClienteRecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => AppClienteRoute,
} as any)
const AppClienteQrRoute = AppClienteQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppClienteRoute,
} as any)
const AppClientePerfilRoute = AppClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppClienteRoute,
} as any)
const AppClienteInicioRoute = AppClienteInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppClienteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/cliente': typeof AppClienteRouteWithChildren
  '/app/cliente/inicio': typeof AppClienteInicioRoute
  '/app/cliente/perfil': typeof AppClientePerfilRoute
  '/app/cliente/qr': typeof AppClienteQrRoute
  '/app/cliente/recompensas': typeof AppClienteRecompensasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/cliente': typeof AppClienteRouteWithChildren
  '/app/cliente/inicio': typeof AppClienteInicioRoute
  '/app/cliente/perfil': typeof AppClientePerfilRoute
  '/app/cliente/qr': typeof AppClienteQrRoute
  '/app/cliente/recompensas': typeof AppClienteRecompensasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/cliente': typeof AppClienteRouteWithChildren
  '/app/cliente/inicio': typeof AppClienteInicioRoute
  '/app/cliente/perfil': typeof AppClientePerfilRoute
  '/app/cliente/qr': typeof AppClienteQrRoute
  '/app/cliente/recompensas': typeof AppClienteRecompensasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/app/cliente'
    | '/app/cliente/inicio'
    | '/app/cliente/perfil'
    | '/app/cliente/qr'
    | '/app/cliente/recompensas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/app/cliente'
    | '/app/cliente/inicio'
    | '/app/cliente/perfil'
    | '/app/cliente/qr'
    | '/app/cliente/recompensas'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/app/cliente'
    | '/app/cliente/inicio'
    | '/app/cliente/perfil'
    | '/app/cliente/qr'
    | '/app/cliente/recompensas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AppClienteRoute: typeof AppClienteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cliente': {
      id: '/app/cliente'
      path: '/app/cliente'
      fullPath: '/app/cliente'
      preLoaderRoute: typeof AppClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cliente/recompensas': {
      id: '/app/cliente/recompensas'
      path: '/recompensas'
      fullPath: '/app/cliente/recompensas'
      preLoaderRoute: typeof AppClienteRecompensasRouteImport
      parentRoute: typeof AppClienteRoute
    }
    '/app/cliente/qr': {
      id: '/app/cliente/qr'
      path: '/qr'
      fullPath: '/app/cliente/qr'
      preLoaderRoute: typeof AppClienteQrRouteImport
      parentRoute: typeof AppClienteRoute
    }
    '/app/cliente/perfil': {
      id: '/app/cliente/perfil'
      path: '/perfil'
      fullPath: '/app/cliente/perfil'
      preLoaderRoute: typeof AppClientePerfilRouteImport
      parentRoute: typeof AppClienteRoute
    }
    '/app/cliente/inicio': {
      id: '/app/cliente/inicio'
      path: '/inicio'
      fullPath: '/app/cliente/inicio'
      preLoaderRoute: typeof AppClienteInicioRouteImport
      parentRoute: typeof AppClienteRoute
    }
  }
}

interface AppClienteRouteChildren {
  AppClienteInicioRoute: typeof AppClienteInicioRoute
  AppClientePerfilRoute: typeof AppClientePerfilRoute
  AppClienteQrRoute: typeof AppClienteQrRoute
  AppClienteRecompensasRoute: typeof AppClienteRecompensasRoute
}

const AppClienteRouteChildren: AppClienteRouteChildren = {
  AppClienteInicioRoute: AppClienteInicioRoute,
  AppClientePerfilRoute: AppClientePerfilRoute,
  AppClienteQrRoute: AppClienteQrRoute,
  AppClienteRecompensasRoute: AppClienteRecompensasRoute,
}

const AppClienteRouteWithChildren = AppClienteRoute._addFileChildren(
  AppClienteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AppClienteRoute: AppClienteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
